package com.fserp.kki.utlis

class Praments {

    var PPOST_USER_ID: String? = null
    var PPOST_TIME: String? = null
    var PPOST_DATE: String? = null
    var PPOST_ID: String? = null
    var PDATEFORMAT: String? = null
    var PEXTRA5: String? = null
    var PEXTRA4: String? = null
    var PEXTRA3: String? = null
    var PD_STATUS: String? = null
    var PCOLOR_FLAG: String? = null
    var PNOTIFICATION_FLAG: String? = null
    var X5: String? = null
    var X4: String? = null
    var X3: String? = null
    var X2: String? = null
    var X1: String? = null
    var PCMP_DETAILS: String? = null
    var PCMP_NATURE: String? = null
    var PWARRANTY_MFG_DATE: String? = null
    var PWARRANTY_COMM_DATE: String? = null
    var PWARRANTY_OUT_DATE: String? = null
    var PCMP_CLOSSINGDATE: String? = null
    var PASSIGN_TIME: String? = null
    var PASSIGN_DATE: String? = null
    var PASSIGN_TO_CODE: String? = null
    var PPRIORITY_CODE: String? = null
    var PCATEGORY_CODE: String? = null
    var PREPORTED_BY: String? = null
    var PCOMPLAINT_SHORT_DESC: String? = null
    var PPRODUCT_CODE: String? = null
    var PLOCO_NO: String? = null
    var PLEDGER_CODE_SUBCODE: String? = null
    var PSUB_LEDGER_CODE: String? = null
    var PLEDGER_CODE: String? = null
    var PCUST_TYPE_CODE: String? = null
    var PCMP_TYPE_CODE: String? = null
    var PDEPTT_CODE: String? = null
    var PCOMPLAINT_TIME: String? = null
    var PCOMPLAINT_DATE: String? = null
    var PCOMPLAINT_TYPE: String? = null
    var PTYPE: String? = null
    var PUSER_ID: String? = null
    var PIP: String? = null
    var PSTATUS: String? = null
    var PX5: String? = null
    var PX4: String? = null
    var PX3: String? = null
    var PX2: String? = null
    var PX1: String? = null
    var PNATURE_CODE: String? = null
    var PROW_ID: String? = null
    var PCOMPLAINT_ID: String? = null
    var PBRANCH_CODE: String? = null
    var PCOMPNAME: String? = null
    var pcenter: String? = null
    var pcompcode: String? = null
    var extra: String? = null
    var PCOMP_CODE: String? = null
    var PCENT_CODE: String? = null
    var PUSER_NAME: String? = null
    var PPASSWORD: String? = null
    var PEXTRA: String? = null
    var COMPLAINT_CODE: String? = null
    var COMPLAINT_NAME: String? = null
    var COMPLAINT_NICK: String? = null
    var pcentcode: String? = null
    var ledgername: String? = null
    var mledgercode: String? = null
    var typeflag: String? = null
    var exptra1: String? = null
    var PCOMPCODE: String? = null
    var PCENTCODE: String? = null
    var PLOCONO: String? = null
    var PSERIALNO: String? = null
    var PEXTRA1: String? = null
    var PEXTRA2: String? = null
    var EXTRA3: String? = null
    var EXTRA2: String? = null
    var PROD_DESC: String? = null
    var priorcode: String? = null
    var PUSERNAME: String? = null
    var NATURE: String? = null
    var PPOST_TYPE:String?=null
    var PPOST_COMMENTS: String? = null
    var PPOST_COMMENTS_SEARCH: String? = null
    var PACTION_TAKEN_REMARKS: String? = null
    var PSOLUTION_REMARKS: String? = null
    var PATTACH_DOC_NAME: String? = null
    var PATTACH_DOC_SIZE: String? = null
    var PATTACH_DOC_TYPE: String? = null
    var PEMAIL_FROM: String? = null
    var PEMAIL_TO: String? = null
    var PEMAIL_CC: String? = null
    var PSENT_STATUS_MAIL: String? = null
    var X6: String? = null
    var X7: String? = null
    var X8: String? = null
    var X9:String?=null
    var X10: String? = null
    var X11: String? = null
    var X12: String? = null
    var X13:String?=null
    var X14:String?=null
    var EQUIPMENTTYPE_NAME:String?=null
    var PFAILURE_NICK:String?=null
    var PEQUIPMENTTYPE_CODE:String?=null
    var PITEM_CODE:String?=null
    var PITEM_NAME:String?=null
    var PCOST:String?=null
    var PSTYPE:String?=null




}